In [2]:
#1. What is a Python library? Why do we use Python libraries?
'''
Ans. Python libraries is a set of prewriiten code and function that we can use again efficiently for our usage.
it makes our programming easy as we dont have to write the code again. Python libraries makes our programming easy'''
import numpy as np 

In [3]:
#2. What is the difference between Numpy array and List?
'''
Ans. Numpy arrays can only store elements of the same data type, typically numerical data types like integers or floats
Python lists can store elements of different data types within the same list.Numpy arrays offer better performance for numerical
computations and operations compared to Python lists. Numpy is implemented in C and optimized for performance, 
whereas Python lists are implemented in Python and are more general-purpose'''

'\nAns. Numpy arrays can only store elements of the same data type, typically numerical data types like integers or floats\nPython lists can store elements of different data types within the same list.Numpy arrays offer better performance for numerical\ncomputations and operations compared to Python lists. Numpy is implemented in C and optimized for performance, \nwhereas Python lists are implemented in Python and are more general-purpose'

In [4]:
#3. Find the shape, size and dimension of the following array?

a =[[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]
arr = np.array(a)
arr.shape

(3, 4)

In [5]:
arr.size

12

In [6]:
arr.ndim

2

In [7]:
#4. Write python code to access the first row of the following array?
a = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(a)
arr[0]

array([1, 2, 3, 4])

In [20]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
a = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(a)
arr[2,3]

12

In [23]:
#6. 6. Write code to extract all odd-indexed elements from the given numpy array?
a = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]
arr = np.array(a)

odd_indexed_elements = arr[:, 1::2]  
print(odd_indexed_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [10]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

a = np.random.rand(3,3)
a

array([[0.57239124, 0.35269556, 0.84667673],
       [0.49096158, 0.37751501, 0.03922158],
       [0.96780639, 0.4699601 , 0.80216522]])

In [ ]:
#8. Describe the difference between np.random.rand and np.random.randn?
'''
numpy.random.randn generates samples from the normal distribution, while numpy.random.rand from a uniform distribution
(in the range [0,1))'''

In [15]:
#9. Write code to increase the dimension of the following array?
a = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]
arr = np.array(a)
arr1 = np.expand_dims(arr,axis = 0)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [16]:
#10. How to transpose the following array in NumPy?
a =[[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(a)
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [25]:
#11. Consider the following matrix:
Matrix_A2 = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix_B2 = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

#Perform the following operation using Python

#1. Index wise application
arr1 = np.array(Matrix_A2)
arr2 = np.array(Matrix_B2)

arr1*arr2


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [34]:
#2. Matrix Multiplication

arr1@ arr2

#matrix multiplication can't be done as the number columns in first matrix does not match with number of rows in second matrix

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [35]:
#3. add both the matrix
arr+arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [36]:
#4. Subtract matrix b from a
arr1 - arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
#5. divide matrix b by a
arr2/arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#12. Which function in Numpy can be used to swap the byte order of an array?
'''
In NumPy, you can use the byteswap method to swap the byte order of an array. This method swaps the byte order of the elements
in the array without changing the data type or the memory layout.'''

In [ ]:
#13. What is the significance of the np.linalg.inv function?
'''
The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix. 
Specifically, it calculates the inverse of a given matrix '''

In [39]:
#14. What does the np.reshape function do, and how is it use?
'''
Ans. It Gives a new shape to an array without changing its data . it sannot change the size of array. after reshaping the 
array the size should be same as the orignal array.'''

#it can be use
a = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]
arr = np.array(a)
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
#15. What is broadcasting in Numpy?
'''
In NumPy, broadcasting refers to the ability of arrays with different shapes to be operated on with arithmetic operations,
without explicitly reshaping or duplicating the data.

'''